#!/bin/bash

# This shell script is an optional tool to simplify
# the installation and usage of laradock with docker-sync.

# Make sure that the DOCKER_SYNC_STRATEGY is set in the .env
# DOCKER_SYNC_STRATEGY=native_osx # osx
# DOCKER_SYNC_STRATEGY=unison # windows

# To run, make sure to add permissions to this file:
# chmod 755 sync.sh

# USAGE EXAMPLE:
# Install docker-sync: ./sync.sh install
# Start sync and services with nginx and mysql: ./sync.sh up nginx mysql
# Stop containers and sync: ./sync.sh down

# prints colored text
print_style () {

    if [ "$2" == "info" ] ; then
        COLOR="96m"
    elif [ "$2" == "success" ] ; then
        COLOR="92m"
    elif [ "$2" == "warning" ] ; then
        COLOR="93m"
    elif [ "$2" == "danger" ] ; then
        COLOR="91m"
    else #default color
        COLOR="0m"
    fi

    STARTCOLOR="\e[$COLOR"
    ENDCOLOR="\e[0m"

    printf "$STARTCOLOR%b$ENDCOLOR" "$1"
}

display_options () {
    printf "可用选项:\n";
    print_style "   install" "info"; printf "\t\t 安装 docker-sync.\n"
    print_style "   up [services]" "success"; printf "\t 启动服务.\n"
    print_style "   down" "success"; printf "\t\t\t 停止服务.\n"
    print_style "   bash" "success"; printf "\t\t\t 以用户laradock打开工作容器终端.\n"
    print_style "   sync" "info"; printf "\t\t\t 手动触发文件同步.\n"
    print_style "   clean" "danger"; printf "\t\t 移除所有文件.\n"
}

if [[ $# -eq 0 ]] ; then
    print_style "缺少参数.\n" "danger"
    display_options
    exit 1
fi

if [ "$1" == "up" ] ; then
    print_style "初始化 docker-sync\n" "info"
    print_style "第一次运行需15分钟以上\n" "info"
    docker-sync start;

    print_style "初始化 docker-compose\n" "info"
    shift # removing first argument
    docker-compose up -d ${@}

elif [ "$1" == "down" ]; then
    print_style "停止 docker-compose\n" "info"
    docker-compose stop

    print_style "正在停止 docker-sync\n" "info"
    docker-sync stop

elif [ "$1" == "bash" ]; then
    docker-compose exec --user=laradock workspace bash

elif [ "$1" == "install" ]; then
    print_style "安装 docker-sync\n" "info"
    gem install docker-sync

elif [ "$1" == "sync" ]; then
    print_style "手动触发同步 between host and docker-sync container.\n" "info"
    docker-sync sync;

elif [ "$1" == "clean" ]; then
    print_style "清除容器中所有文件.\n" "warning"
    docker-sync clean
else
    print_style "不合法参数.\n" "danger"
    display_options
    exit 1
fi
